FROM ubuntu:20.04
WORKDIR /app

RUN apt update && apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt update && apt install -y nodejs && node -v && npm -v && \
    rm -rf /var/lib/apt/lists/* 

ENV REACT_APP_BACKEND_URL http://localhost:8000
CMD npm install && npm install -g serve && npm run build && serve -s -l 5000 build

